### ISSUE TITLE
post_link(media_link, media_link_preview, text)

### ISSUE THREAD

**Issue by kaue** [shayanb/RE-Plague#2]
media_link and media_link_preview

Should be a http://s.plague.io/upload/... url.

There is anymethod the app uses to copy pictures to plague server?

Thanks

**Comment by shayanb** [comment]
photo_post() method is implemented with the right url and variables, but the POST header must be modified to accept the proper file format, I haven't got the time to fix it yet.

**Comment by borazslo** [comment]
I think it is not only about the POST header. If you change the `Line198` to 
`	url = "http://plague.io/api/upload/?uid="+u_id+"&token="+token`, the authentication works and the error message changes to `{"error": {"code": "API_BadParams", "info": null}}`
- (If you misspell the line to `uuid="+u_id' the error messages speaks about a failed authentication.)
- (If you modify the header for file uploading with urllib3, the error message is still about API_BadParams)
